"""create_transaction_items_table

Revision ID: 512c3dc8a9bd
Revises: 558e19a7fc71
Create Date: 2026-03-27 19:51:18.205380

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "512c3dc8a9bd"
down_revision = "558e19a7fc71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_items",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("transaction_id", sa.INTEGER(), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("price", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_items")),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_transaction_items_transaction_id_transactions"),
            ondelete="CASCADE",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_items")
    # ### end Alembic commands ###
