"""add_status_to_transactions_table

Revision ID: 558e19a7fc71
Revises: bd0ced0cd102
Create Date: 2026-03-27 19:23:06.709803

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "558e19a7fc71"
down_revision = "bd0ced0cd102"
branch_labels = None
depends_on = None


# add status column to transactions table
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("store_id", sa.INTEGER(), nullable=True))
    op.add_column("transactions", sa.Column("status", sa.String(length=50), nullable=False, server_default="pending"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "store_id")
    op.drop_column("transactions", "status")
    # ### end Alembic commands ###
