# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import catalog_svc_pb2 as catalog__svc__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in catalog_svc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStoreByUuid = channel.unary_unary(
                '/catalog_svc.CatalogService/GetStoreByUuid',
                request_serializer=catalog__svc__pb2.GetStoreByUuidRequest.SerializeToString,
                response_deserializer=catalog__svc__pb2.GetStoreByUuidResponse.FromString,
                _registered_method=True)
        self.GetProductsByUuids = channel.unary_unary(
                '/catalog_svc.CatalogService/GetProductsByUuids',
                request_serializer=catalog__svc__pb2.GetProductsByUuidsRequest.SerializeToString,
                response_deserializer=catalog__svc__pb2.GetProductsByUuidsResponse.FromString,
                _registered_method=True)
        self.ReserveStocks = channel.unary_unary(
                '/catalog_svc.CatalogService/ReserveStocks',
                request_serializer=catalog__svc__pb2.ReserveStocksRequest.SerializeToString,
                response_deserializer=catalog__svc__pb2.ReserveStocksResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStoreByUuid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductsByUuids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveStocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStoreByUuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStoreByUuid,
                    request_deserializer=catalog__svc__pb2.GetStoreByUuidRequest.FromString,
                    response_serializer=catalog__svc__pb2.GetStoreByUuidResponse.SerializeToString,
            ),
            'GetProductsByUuids': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductsByUuids,
                    request_deserializer=catalog__svc__pb2.GetProductsByUuidsRequest.FromString,
                    response_serializer=catalog__svc__pb2.GetProductsByUuidsResponse.SerializeToString,
            ),
            'ReserveStocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveStocks,
                    request_deserializer=catalog__svc__pb2.ReserveStocksRequest.FromString,
                    response_serializer=catalog__svc__pb2.ReserveStocksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalog_svc.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalog_svc.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStoreByUuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog_svc.CatalogService/GetStoreByUuid',
            catalog__svc__pb2.GetStoreByUuidRequest.SerializeToString,
            catalog__svc__pb2.GetStoreByUuidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductsByUuids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog_svc.CatalogService/GetProductsByUuids',
            catalog__svc__pb2.GetProductsByUuidsRequest.SerializeToString,
            catalog__svc__pb2.GetProductsByUuidsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveStocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog_svc.CatalogService/ReserveStocks',
            catalog__svc__pb2.ReserveStocksRequest.SerializeToString,
            catalog__svc__pb2.ReserveStocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
