# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog_svc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'catalog_svc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61talog_svc.proto\x12\x0b\x63\x61talog_svc\"+\n\x15GetStoreByUuidRequest\x12\x12\n\nstore_uuid\x18\x01 \x01(\t\"#\n\x05Store\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\";\n\x16GetStoreByUuidResponse\x12!\n\x05store\x18\x01 \x01(\x0b\x32\x12.catalog_svc.Store\"F\n\x19GetProductsByUuidsRequest\x12\x12\n\nstore_uuid\x18\x01 \x01(\t\x12\x15\n\rproduct_uuids\x18\x02 \x03(\t\"4\n\x07Product\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x03\"D\n\x1aGetProductsByUuidsResponse\x12&\n\x08products\x18\x01 \x03(\x0b\x32\x14.catalog_svc.Product\"3\n\tStockItem\x12\x14\n\x0cproduct_uuid\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"=\n\x14ReserveStocksRequest\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.catalog_svc.StockItem\"9\n\x15ReserveStocksResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xaa\x02\n\x0e\x43\x61talogService\x12Y\n\x0eGetStoreByUuid\x12\".catalog_svc.GetStoreByUuidRequest\x1a#.catalog_svc.GetStoreByUuidResponse\x12\x65\n\x12GetProductsByUuids\x12&.catalog_svc.GetProductsByUuidsRequest\x1a\'.catalog_svc.GetProductsByUuidsResponse\x12V\n\rReserveStocks\x12!.catalog_svc.ReserveStocksRequest\x1a\".catalog_svc.ReserveStocksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_svc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTOREBYUUIDREQUEST']._serialized_start=34
  _globals['_GETSTOREBYUUIDREQUEST']._serialized_end=77
  _globals['_STORE']._serialized_start=79
  _globals['_STORE']._serialized_end=114
  _globals['_GETSTOREBYUUIDRESPONSE']._serialized_start=116
  _globals['_GETSTOREBYUUIDRESPONSE']._serialized_end=175
  _globals['_GETPRODUCTSBYUUIDSREQUEST']._serialized_start=177
  _globals['_GETPRODUCTSBYUUIDSREQUEST']._serialized_end=247
  _globals['_PRODUCT']._serialized_start=249
  _globals['_PRODUCT']._serialized_end=301
  _globals['_GETPRODUCTSBYUUIDSRESPONSE']._serialized_start=303
  _globals['_GETPRODUCTSBYUUIDSRESPONSE']._serialized_end=371
  _globals['_STOCKITEM']._serialized_start=373
  _globals['_STOCKITEM']._serialized_end=424
  _globals['_RESERVESTOCKSREQUEST']._serialized_start=426
  _globals['_RESERVESTOCKSREQUEST']._serialized_end=487
  _globals['_RESERVESTOCKSRESPONSE']._serialized_start=489
  _globals['_RESERVESTOCKSRESPONSE']._serialized_end=546
  _globals['_CATALOGSERVICE']._serialized_start=549
  _globals['_CATALOGSERVICE']._serialized_end=847
# @@protoc_insertion_point(module_scope)
